### ISSUE TITLE
Requesting a different region?

### ISSUE THREAD

**Issue by Nakroma** [blizzapi/blizzapi#324]
Hey, is it currently possible to change the region for different queries from the one you initialized the BlizzAPI instance with? This behaviour is fine for static data, but for example if I wanted to get WoW auction house or token prices for different regions I'd have to initialize a new client everytime I request a different region. US access tokens work for EU/KR... etc. as well, so I think this should be possible to do (maybe it is already, couldn't find anything in the code though).

If not, I'd maybe propose either a region parameter on the query function that overrides the BlizzAPI instance region if set, or have a `.setRegion()` function on the BlizzAPI class.

**Comment by lwojcik** [comment]
Hi @Nakroma! Thanks for the message.

I'm not super versed in WoW APIs and I can't provide an immediate answer. I'll check that and get back to you.

Also paging @AlexZeDim - have you by any chance had this exact scenario?

**Comment by AlexZeDim** [comment]
Hello everyone! Hi, @lwojcik haven't seen each other for a while.

I am understanding your problem @Nakroma very well since Blizzard add `commodities` endpoint and make auctions house data cross-realm.  

> *If not, I'd maybe propose either a region parameter on the query function that overrides the BlizzAPI instance region if set, or have a .setRegion() function on the BlizzAPI class.*

Guess it's possible to do it, but I do not remember it for now, should check the code, but the main problem here should be not changing the region but changing the querying a region.

**Comment by lwojcik** [comment]
I released [`v2.3.3-next.0`](https://www.npmjs.com/package/blizzapi/v/2.3.3-next.0) on npm which adds two options:

* ability to override region setting at any time with `setRegion` method
* accepting `region` as a property of `options` object passed to `query` method

@Nakroma @AlexZeDim could you check it out and let me know if that works?

**Comment by Nakroma** [comment]
Hey @lwojcik, thanks for getting back to this so quickly! Both the `setRegion` method and passing `region` to `query` works for me when testing locally, using `v2.3.3-next.0`.

**Comment by lwojcik** [comment]
Merged to main and released in [v2.4.0](https://www.npmjs.com/package/blizzapi/v/2.4.0).

I messed up semver versioning with that `.next.0` release but nevermind, we're back on track. :)

Please let me know in case you needed anything else!
