### ISSUE TITLE
getting access_token expiration data

### ISSUE THREAD

**Issue by bonesoul** [blizzapi/blizzapi#334]
blizz api returns a response similar to:

```
Example CURL request
curl -u {client_id}:{client_secret} -d grant_type=client_credentials https://oauth.battle.net/token
Expected response
{"access_token": "USVb1nGO9kwQlhNRRnI4iWVy2UV5j7M6h7", "token_type": "bearer", "expires_in": 86399, "scope": "example.scope"}
```

blizz api (https://blizzapi.lukem.net/docs/usage/getting-access-token.html) getAccessToken() just returns the token but I also need the expires_in data to store and use in my internal authentication mechanisms.

How can I get the expires_in?

does BlizzAPI.validateAccessToken() return the data?

**Comment by lwojcik** [comment]
Update: I'm working on this and I'm gonna handle this issue first before picking up #333.

I'm adding a method `getAccessTokenObject` that will expose full access token object as returned from Battle.net API. There's still a little internal refactoring to be done but I'll release test version shortly.

**Comment by bonesoul** [comment]
thanks for your work.

**Comment by lwojcik** [comment]
I added relevant [getAccessTokenObject method](https://blizzapi.lukem.net/docs/usage/getting-access-token.html#getaccesstokenobject) in [v2.5.0](https://www.npmjs.com/package/blizzapi/v/2.5.0).
